"""Series character cards for Project Phenix (ޕްރޮޖެކްޓް ފީނިކްސް) — a Maldivian police crime thriller: investigator
Ashham and analyst Habeeb uncover a secret human-testing drug lab under a deserted island in Gaafu Alifu atoll.
Creates card.json only for characters that don't exist yet. All references are text-only (the poster shows Ashham from
behind).
Usage: python characters_phenix.py <series_dir> <first_episode>
"""
import json, os, sys

MV = "Maldivian, South Asian features, warm brown skin"
CARDS = [
    dict(id="ashham", name="Ashham", name_dhivehi="އަޝްހަމް",
         role="protagonist; the Maldives Police Serious Crimes Department's best investigator, about 38; tall, strong, sharp-witted, calm under pressure",
         gender="male", age="about 38",
         ethnicity_look=MV,
         face="strong rectangular face with a firm jaw, sharp intelligent dark eyes under straight thick eyebrows, short dark stubble",
         hair="short neat black hair, tapered at the sides",
         build="tall, broad-shouldered, strong",
         default_outfit="a dark-navy long-sleeved police field shirt with buttoned cuffs and plain shoulder epaulettes (no badges, no lettering), dark-navy trousers, a plain black belt, black boots, a black wristwatch",
         distinguishing_features="dark-navy field shirt, short tapered hair, stubble, intense focused gaze",
         personality_cues="focused, determined, protective, rarely smiles",
         visual_prompt="Ashham: a tall broad-shouldered strong Maldivian man of about 38 with warm brown skin, a strong rectangular face with a firm jaw, sharp intelligent dark eyes under straight thick eyebrows, short neat black hair tapered at the sides and short dark stubble; wears a dark-navy long-sleeved police field shirt with buttoned cuffs and plain epaulettes (no badges, no lettering), dark-navy trousers, a plain black belt, black boots and a black wristwatch."),
    dict(id="habeeb", name="Habeeb", name_dhivehi="ޙަބީބު",
         role="Ashham's partner; the country's best data-analysis and digital-forensics officer, about 28; brave despite his fear (the narrator sometimes calls him Zayaan — same person)",
         gender="male", age="about 28",
         ethnicity_look=MV,
         face="slim youthful face, clean-shaven, alert dark eyes behind thin rectangular black-rimmed glasses",
         hair="short black hair, slightly messy on top",
         build="slim, average height",
         default_outfit="a dark-grey long-sleeved zip-up jacket over a plain white t-shirt, black trousers, white sneakers, a black laptop backpack, thin black-rimmed glasses",
         distinguishing_features="black-rimmed glasses, dark-grey zip jacket, laptop or tablet in hand",
         personality_cues="quick, nervous, loyal, focused on screens",
         visual_prompt="Habeeb: a slim Maldivian young man of about 28 with warm brown skin, a slim clean-shaven youthful face, alert dark eyes behind thin rectangular black-rimmed glasses and short slightly messy black hair; wears a dark-grey long-sleeved zip-up jacket over a plain white t-shirt, black trousers and white sneakers."),
    dict(id="moosa", name="Moosa Thaahir", name_dhivehi="މޫސާ ޠާހިރު",
         role="one of Malé's most powerful tycoons, about 62; Naail's father; secretly funds the lab and later sides with Fairooz",
         gender="male", age="about 62",
         ethnicity_look=MV,
         face="heavy lined face, tired dark eyes behind thin gold-rimmed glasses, a neatly trimmed short white beard",
         hair="thin combed-back grey hair",
         build="heavy-set, average height",
         default_outfit="an expensive dark-navy suit with a long-sleeved white shirt and a plain dark-red tie, a gold wristwatch",
         distinguishing_features="gold-rimmed glasses, white beard, navy suit with dark-red tie",
         personality_cues="grief-stricken on the surface, evasive, anxious",
         visual_prompt="Moosa Thaahir: a heavy-set Maldivian man of about 62 with warm brown skin, a heavy lined face, tired dark eyes behind thin gold-rimmed glasses, thin combed-back grey hair and a neatly trimmed short white beard; wears an expensive dark-navy suit with a long-sleeved white shirt, a plain dark-red tie and a gold wristwatch."),
    dict(id="naail", name="Naail Moosa", name_dhivehi="ނާއިލް މޫސާ",
         role="Moosa's younger son, about 25, a rich Malé party boy; discovered the island lab and was killed for trying to expose it (only ever shown ALIVE: in a framed photo, a phone-call memory or a dark flashback)",
         gender="male", age="about 25",
         ethnicity_look=MV,
         face="handsome youthful face, restless dark eyes, a thin neatly trimmed beard along the jaw",
         hair="black hair styled short at the sides and longer on top",
         build="slim, athletic",
         default_outfit="a black long-sleeved bomber jacket over a dark-red t-shirt, black jeans, white sneakers, a silver wristwatch",
         distinguishing_features="black bomber jacket, styled hair, thin beard",
         personality_cues="restless, frightened, guilty",
         visual_prompt="Naail: a slim athletic Maldivian young man of about 25 with warm brown skin, a handsome youthful face, restless dark eyes, black hair styled short at the sides and longer on top and a thin neatly trimmed beard along the jaw; wears a black long-sleeved bomber jacket over a dark-red t-shirt, black jeans and white sneakers."),
    dict(id="kalhe", name="Kalhe", name_dhivehi="ކަޅޭ",
         role="about 40; leader of the Maafannu 'Black Wolf' gang; smuggled the lab's cargo out of Malé port for Naail",
         gender="male", age="about 40",
         ethnicity_look=MV,
         face="hard square face, a long pale scar across his left cheek, heavy-lidded dark eyes, a short black goatee",
         hair="shaved head",
         build="stocky, heavily built",
         default_outfit="a black long-sleeved henley shirt with the cuffs buttoned, dark cargo trousers, black boots, a thick black leather wristband",
         distinguishing_features="shaved head, long scar on the left cheek, goatee, all black clothes",
         personality_cues="smug, guarded, unexpectedly candid",
         visual_prompt="Kalhe: a stocky heavily built Maldivian man of about 40 with warm brown skin, a shaved head, a hard square face with a long pale scar across his left cheek, heavy-lidded dark eyes and a short black goatee; wears a black long-sleeved henley shirt with buttoned cuffs, dark cargo trousers and black boots."),
    dict(id="raniya", name="Dr. Raniya", name_dhivehi="ޑޮކްޓަރ ރާނިޔާ",
         role="about 28; chief surgeon of the Gaafu Alifu atoll hospital in Villingili; forced to help the lab because they hold her father hostage",
         gender="female", age="about 28",
         ethnicity_look=MV,
         face="beautiful oval face with fair-brown skin, large serious dark eyes, softly arched eyebrows, a small straight nose",
         hair="fully covered by a navy-blue hijab",
         build="slim, average height",
         default_outfit="a white long-sleeved doctor's coat over a loose long-sleeved ankle-length dusty-blue dress, a navy-blue hijab wrapped snugly and fully covering her hair and neck, flat dark shoes",
         distinguishing_features="white doctor's coat, navy hijab, dusty-blue dress, serious composed face",
         personality_cues="serious, brave but frightened, devoted daughter",
         visual_prompt="Dr. Raniya: a slim Maldivian woman of about 28 with fair-brown skin, a beautiful oval face, large serious dark eyes, softly arched eyebrows and a small straight nose; wears a white long-sleeved doctor's coat over a loose long-sleeved ankle-length dusty-blue dress and a navy-blue hijab wrapped snugly and fully covering her hair and neck."),
    dict(id="raniya_father", name="Raniya's father", name_dhivehi="ރާނިޔާގެ ބައްޕަ",
         role="about 62; held hostage in the island lab's isolation ward and used in the drug tests; rescued by Ashham, recovers by the finale",
         gender="male", age="about 62",
         ethnicity_look=MV,
         face="thin gaunt kind face, sunken tired eyes, short white stubble beard",
         hair="short thinning white hair",
         build="thin, frail",
         default_outfit="a loose pale-grey long-sleeved patient tunic and loose pale-grey trousers",
         distinguishing_features="thin and frail, white stubble, pale-grey patient clothes",
         personality_cues="weak, gentle, loving",
         visual_prompt="Raniya's father: a thin frail Maldivian man of about 62 with warm brown skin, a thin gaunt kind face, sunken tired eyes, short thinning white hair and short white stubble; wears a loose pale-grey long-sleeved patient tunic and loose pale-grey trousers."),
    dict(id="fairooz", name="Assistant Commissioner Fairooz", name_dhivehi="ފައިރޫޒް",
         role="about 52; Assistant Commissioner of the Malé Area Command, Ashham's direct boss; secretly runs the lab's protection and ordered Naail's killing",
         gender="male", age="about 52",
         ethnicity_look=MV,
         face="broad hard face, cold narrow dark eyes, a thick black moustache streaked with grey, deep frown lines",
         hair="short black hair greying at the temples, receding hairline",
         build="tall, heavy-set, imposing",
         default_outfit="a senior officer's dark-navy long-sleeved police dress uniform buttoned to the collar, plain silver insignia on the epaulettes (no lettering), a black belt, dark-navy trousers",
         distinguishing_features="thick greying moustache, senior navy dress uniform with silver epaulettes, cold stare",
         personality_cues="arrogant, ruthless, smug",
         visual_prompt="Fairooz: a tall heavy-set imposing Maldivian man of about 52 with warm brown skin, a broad hard face, cold narrow dark eyes, a thick black moustache streaked with grey, deep frown lines and short black hair greying at the temples with a receding hairline; wears a senior officer's dark-navy long-sleeved police dress uniform buttoned to the collar with plain silver insignia on the epaulettes (no lettering) and a black belt."),
    dict(id="faahid", name="Faahid", name_dhivehi="ފާހިދު",
         role="about 62; retired Police Commissioner forced out for opposing Fairooz; shelters the team in his Hulhumalé flat, brings in the MNDF; becomes the new Commissioner in the finale",
         gender="male", age="about 62",
         ethnicity_look=MV,
         face="dignified lean face, wise steady dark eyes, a neatly trimmed white moustache",
         hair="short neat grey hair",
         build="lean, upright, average height",
         default_outfit="a dark-olive long-sleeved button-up shirt, charcoal-grey trousers, black shoes, a steel wristwatch",
         distinguishing_features="white moustache, grey hair, upright bearing, olive shirt",
         personality_cues="calm, principled, fatherly",
         visual_prompt="Faahid: a lean upright Maldivian man of about 62 with warm brown skin, a dignified lean face, wise steady dark eyes, short neat grey hair and a neatly trimmed white moustache; wears a dark-olive long-sleeved button-up shirt, charcoal-grey trousers and a steel wristwatch."),
    dict(id="naasir", name="Naasir", name_dhivehi="ނާޞިރު",
         role="about 46; head of the police Internal Affairs (and a senior prison officer); secretly on Minister Saleem's side; seizes the hard drive and holds Habeeb at Dhoonidhoo",
         gender="male", age="about 46",
         ethnicity_look=MV,
         face="narrow sharp face, small cold dark eyes, a thin black goatee",
         hair="completely bald head",
         build="lean, wiry, average height",
         default_outfit="a black suit with a long-sleeved charcoal shirt and a plain black tie, black shoes",
         distinguishing_features="bald head, thin goatee, all-black suit",
         personality_cues="smooth, cold, menacing",
         visual_prompt="Naasir: a lean wiry Maldivian man of about 46 with warm brown skin, a completely bald head, a narrow sharp face, small cold dark eyes and a thin black goatee; wears a black suit with a long-sleeved charcoal shirt and a plain black tie."),
    dict(id="saleem", name="Home Minister Saleem", name_dhivehi="މުޙައްމަދު ސަލީމް",
         role="about 60; the Home Minister, true power behind Project Phenix in the Maldives (leased the island to the foreign pharmaceutical company)",
         gender="male", age="about 60",
         ethnicity_look=MV,
         face="round fleshy face, calm calculating dark eyes behind rimless glasses, clean-shaven, a faint smug smile",
         hair="thick silver hair combed neatly back",
         build="plump, average height",
         default_outfit="an expensive black three-piece suit with a long-sleeved white shirt and a silver-grey silk tie, a gold wristwatch",
         distinguishing_features="silver combed-back hair, rimless glasses, black three-piece suit",
         personality_cues="smooth, untroubled, quietly menacing",
         visual_prompt="Minister Saleem: a plump Maldivian man of about 60 with warm brown skin, a round fleshy clean-shaven face, calm calculating dark eyes behind rimless glasses, thick silver hair combed neatly back and a faint smug smile; wears an expensive black three-piece suit with a long-sleeved white shirt, a silver-grey silk tie and a gold wristwatch."),
    dict(id="vance", name="Dr. Vance", name_dhivehi="ޑޮކްޓަރ ވެންސް",
         role="about 66; the foreign scientist who owns and runs Project Phenix; speaks English; the true mastermind (episode 324)",
         gender="male", age="about 66",
         ethnicity_look="elderly European man, pale skin",
         face="gaunt pale face, cold pale-grey eyes, a thin arrogant mouth, clean-shaven",
         hair="slicked-back silver-white hair",
         build="tall, thin",
         default_outfit="a long black wool overcoat over a black turtleneck, black trousers, black leather gloves",
         distinguishing_features="silver slicked-back hair, long black overcoat, pale cold eyes",
         personality_cues="arrogant, contemptuous, icy",
         visual_prompt="Dr. Vance: a tall thin elderly European man of about 66 with pale skin, a gaunt clean-shaven face, cold pale-grey eyes, a thin arrogant mouth and slicked-back silver-white hair; wears a long black wool overcoat over a black turtleneck, black trousers and black leather gloves."),
]

FIRST = dict(ashham=311, habeeb=311, moosa=311, naail=311, kalhe=318, raniya=318, raniya_father=321,
             fairooz=321, faahid=322, naasir=323, saleem=323, vance=324)

if __name__ == "__main__":
    series_dir, episode = sys.argv[1], int(sys.argv[2])
    for c in CARDS:
        d = os.path.join(series_dir, "characters", c["id"])
        p = os.path.join(d, "card.json")
        if os.path.exists(p):
            continue
        os.makedirs(d, exist_ok=True)
        card = dict(c)
        card["first_seen_episode"] = FIRST.get(c["id"], episode)
        card["reference_from_cover"] = False
        json.dump(card, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        print("new", c["id"])
