"""Series character cards for Tedhuveriloabi. Creates card.json only for characters that don't exist yet.
Usage: python characters_tedhuveriloabi.py <series_dir> <first_episode>
"""
import json, os, sys

CARDS = [
    dict(id="layaali", name="Layaali", name_dhivehi="ލަޔާލީ",
         role="protagonist; honest, humble finance officer at Rafhaan Group from a poor family; later Rafhaan's wife, head of finance and mother of Raina",
         gender="female", age="mid 20s",
         ethnicity_look="Maldivian, South Asian features, warm light-brown skin",
         face="soft oval face, large warm brown eyes with long lashes, dark softly arched eyebrows, straight nose, gentle full lips",
         hair="fully covered by headscarf",
         build="slim, average height",
         default_outfit="loose ankle-length black abaya with ruffled mauve floral cuffs, black chiffon hijab fully covering hair and neck",
         distinguishing_features="the heroine in front on the series cover",
         personality_cues="modest, gentle, often looking down; quiet strength",
         visual_prompt="Layaali: a Maldivian young woman in her mid 20s with warm light-brown skin, a soft oval face, large warm brown eyes with long lashes, dark softly arched eyebrows and gentle full lips, slim build; wears a loose ankle-length black abaya with ruffled mauve floral cuffs and a black chiffon hijab fully covering her hair and neck.",
         reference_from_cover=True, cover_crop=[0.55, 0.19, 1.0, 0.70]),
    dict(id="rafhaan", name="Rafhaan", name_dhivehi="ރަފްހާން",
         role="young, kind, self-made CEO of Rafhaan Group in Malé; loves Layaali, later her husband",
         gender="male", age="about 30",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="handsome, well-groomed short dark beard, warm dark-brown eyes, straight eyebrows, confident gentle smile",
         hair="short dark-brown hair neatly swept back",
         build="tall, fit",
         default_outfit="tailored black suit, crisp white shirt, slim dark-grey tie, silver wristwatch",
         distinguishing_features="the man at the desk on the series cover",
         personality_cues="calm authority, fair, protective",
         visual_prompt="Rafhaan: a tall fit Maldivian man about 30 with light-brown skin, short dark-brown hair neatly swept back, a well-groomed short dark beard and warm dark-brown eyes; wears a tailored black suit, a crisp white shirt, a slim dark-grey tie and a silver wristwatch.",
         reference_from_cover=True, cover_crop=[0.03, 0.15, 0.45, 0.53]),
    dict(id="ahna", name="Ahna", name_dhivehi="އަހްނާ",
         role="head of finance at Rafhaan Group, rich and arrogant, obsessed with Rafhaan; frames Layaali; jailed, released after 3 years, schemes again",
         gender="female", age="mid 20s",
         ethnicity_look="Maldivian, South Asian features, fair light skin",
         face="strikingly beautiful, high cheekbones, sharp winged eyeliner, glossy deep-red lips, haughty dark eyes",
         hair="covered by headscarf",
         build="slim, tall",
         default_outfit="luxurious ankle-length black abaya with ornate gold-embroidered cuffs, deep burgundy satin hijab fully covering hair and neck, small gold designer handbag",
         distinguishing_features="the woman standing behind the desk on the series cover; burgundy hijab",
         personality_cues="smug, cold smile, raised chin, jealous glare",
         visual_prompt="Ahna: a slim tall Maldivian young woman in her mid 20s with fair light skin, strikingly beautiful with high cheekbones, sharp winged eyeliner, glossy deep-red lips and haughty dark eyes; wears a luxurious ankle-length black abaya with ornate gold-embroidered cuffs and a deep burgundy satin hijab fully covering her hair and neck.",
         reference_from_cover=True, cover_crop=[0.30, 0.08, 0.64, 0.46]),
    dict(id="zoya", name="Zoya", name_dhivehi="ޒޯޔާ",
         role="one of Ahna's two scheming rich 'devil' friends; has contacts inside the bank",
         gender="female", age="late 20s",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="narrow face, perfectly shaped eyebrows, bold makeup, mocking half smile",
         hair="covered by headscarf",
         build="slim",
         default_outfit="emerald-green satin hijab fully covering hair and neck, long-sleeved ankle-length black coat-dress with gold buttons, long manicured nails",
         distinguishing_features="emerald-green hijab, long manicured nails",
         personality_cues="sly, laughs at others",
         visual_prompt="Zoya: a slim Maldivian woman in her late 20s with light-brown skin, a narrow face, perfectly shaped eyebrows, bold makeup and a mocking half smile; wears an emerald-green satin hijab fully covering her hair and neck and a long-sleeved ankle-length black coat-dress with gold buttons; long manicured nails."),
    dict(id="raaya", name="Raaya", name_dhivehi="ރާޔާ",
         role="Ahna's other 'devil' friend; hires a fake nurse to poison Layaali",
         gender="female", age="late 20s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="angular face, narrow cold eyes, thin dark lips, sharp chin",
         hair="covered by headscarf",
         build="slim, medium height",
         default_outfit="charcoal-grey satin hijab fully covering hair and neck, long-sleeved ankle-length dark slate abaya with silver trim, silver statement ring",
         distinguishing_features="charcoal-grey hijab, cold stare",
         personality_cues="cold, calculating, menacing",
         visual_prompt="Raaya: a slim Maldivian woman in her late 20s with medium-brown skin, an angular face, narrow cold eyes and thin dark lips; wears a charcoal-grey satin hijab fully covering her hair and neck and a long-sleeved ankle-length dark slate abaya with silver trim."),
    dict(id="aminath", name="Aminath", name_dhivehi="އާމިނަތު",
         role="Layaali's mother; caring, poor, anxious",
         gender="female", age="early 50s",
         ethnicity_look="Maldivian, South Asian features, warm medium-brown skin",
         face="round gentle face, tired kind eyes, faint worry lines",
         hair="covered by headscarf",
         build="short, plump",
         default_outfit="faded lilac floral cotton dress, long-sleeved and ankle-length, plain white cotton headscarf covering hair and neck",
         distinguishing_features="plain white headscarf",
         personality_cues="worried, loving, prays often",
         visual_prompt="Aminath: a short plump Maldivian woman in her early 50s with warm medium-brown skin, a round gentle face and tired kind eyes; wears a faded lilac floral long-sleeved ankle-length cotton dress and a plain white cotton headscarf covering her hair and neck."),
    dict(id="qaasim", name="Qaasim", name_dhivehi="ޤާސިމް",
         role="Layaali's father; bedridden with a lung illness; once owner of 'Qaasim Enterprises' until Zaahir defrauded him 30 years ago",
         gender="male", age="early 60s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="thin frail face, sunken cheeks, short grey stubble, kind tired eyes",
         hair="short grey hair",
         build="thin, frail",
         default_outfit="faded light-blue long-sleeved cotton shirt and a dark checked sarong (feyli)",
         distinguishing_features="frail, usually lying or sitting in bed, coughing",
         personality_cues="gentle, dignified, sorrowful",
         ref_pose="left: head-and-shoulders portrait; right: full-body view sitting on the edge of a simple bed",
         visual_prompt="Qaasim: a thin frail Maldivian man in his early 60s with medium-brown skin, a thin face with sunken cheeks, short grey hair, short grey stubble and kind tired eyes; wears a faded light-blue long-sleeved cotton shirt and a dark checked sarong."),
    dict(id="khadeeja", name="Khadeeja", name_dhivehi="ޚަދީޖާ",
         role="Rafhaan's mother; status-conscious, pushes the business marriage with Ahna; later accepts Layaali",
         gender="female", age="mid 50s",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="elegant oval face, fine features, sharp dark eyes, subtle makeup",
         hair="covered by headscarf",
         build="slim, upright posture",
         default_outfit="navy-blue long-sleeved ankle-length embroidered kaftan, pearl-grey silk hijab draped neatly over hair and neck, pearl stud earrings hidden under the hijab",
         distinguishing_features="pearl-grey silk hijab",
         personality_cues="proud, anxious about wealth, later warm",
         visual_prompt="Khadeeja: an elegant slim Maldivian woman in her mid 50s with light-brown skin, an elegant oval face, fine features and sharp dark eyes; wears a navy-blue long-sleeved ankle-length embroidered kaftan and a pearl-grey silk hijab draped neatly over her hair and neck."),
    dict(id="ibrahim", name="Ibrahim Faahim", name_dhivehi="އިބްރާހީމް ފާހިމް",
         role="Rafhaan's father; kind, just, supports the marriage to Layaali",
         gender="male", age="early 60s",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="kind face, neatly trimmed white beard, warm eyes, silver-rimmed glasses",
         hair="short grey hair",
         build="medium build",
         default_outfit="cream long-sleeved button shirt and beige trousers",
         distinguishing_features="white beard, silver-rimmed glasses",
         personality_cues="calm, warm smile",
         visual_prompt="Ibrahim Faahim: a Maldivian man in his early 60s with light-brown skin, short grey hair, a neatly trimmed white beard, warm eyes and silver-rimmed glasses; wears a cream long-sleeved button shirt and beige trousers."),
    dict(id="zaahir", name="Ahmed Zaahir", name_dhivehi="އަޙްމަދު ޒާހިރު",
         role="Ahna's father; powerful businessman and biggest shareholder; 30 years ago defrauded Qaasim and founded 'Zaahir Investments'",
         gender="male", age="early 60s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="broad heavy face, thick salt-and-pepper moustache, cold narrow eyes, deep frown lines",
         hair="slicked-back grey hair",
         build="heavy-set",
         default_outfit="charcoal-grey three-piece suit, white shirt, maroon tie, gold wristwatch",
         distinguishing_features="thick moustache, gold watch",
         personality_cues="domineering, threatening",
         visual_prompt="Ahmed Zaahir: a heavy-set Maldivian man in his early 60s with medium-brown skin, a broad heavy face, a thick salt-and-pepper moustache, slicked-back grey hair and cold narrow eyes; wears a charcoal-grey three-piece suit, a white shirt, a maroon tie and a gold wristwatch."),
    dict(id="aasim", name="Aasim", name_dhivehi="އާސިމް",
         role="head of IT at Rafhaan Group and Rafhaan's most trusted friend; finds the digital evidence every time",
         gender="male", age="about 30",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="friendly face, rectangular black-framed glasses, light stubble, alert eyes",
         hair="short neat black hair",
         build="slim, medium height",
         default_outfit="light-blue long-sleeved button shirt, navy trousers, often carrying a laptop",
         distinguishing_features="black-framed glasses, laptop",
         personality_cues="loyal, focused, quick",
         visual_prompt="Aasim: a slim Maldivian man about 30 with medium-brown skin, short neat black hair, rectangular black-framed glasses and light stubble; wears a light-blue long-sleeved button shirt and navy trousers."),
    dict(id="shiyaz", name="Shiyaz", name_dhivehi="ޝިޔާޒް",
         role="Ahna's cousin, foreign-educated IT graduate who leaks company data in Layaali's name",
         gender="male", age="mid 20s",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="lean face, thin moustache and goatee, sly narrow eyes, sly smile",
         hair="black hair slicked back with short sides",
         build="lean",
         default_outfit="dark olive-green polo shirt, black trousers",
         distinguishing_features="thin goatee, sly smile",
         personality_cues="innocent act hiding cunning",
         visual_prompt="Shiyaz: a lean Maldivian young man in his mid 20s with light-brown skin, black hair slicked back with short sides, a thin moustache and goatee and sly narrow eyes; wears a dark olive-green polo shirt and black trousers."),
    dict(id="naasif", name="Naasif", name_dhivehi="ނާޞިފް",
         role="greedy legal adviser of Zaahir Investments; arranges the bank archive fire",
         gender="male", age="late 40s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="balding head, thin-rimmed glasses, thin moustache, shifty eyes",
         hair="balding, short black hair at the sides",
         build="average, slightly paunchy",
         default_outfit="dark grey suit, light-grey shirt, black tie, leather briefcase",
         distinguishing_features="balding, briefcase",
         personality_cues="nervous, greedy",
         visual_prompt="Naasif: a slightly paunchy Maldivian man in his late 40s with medium-brown skin, a balding head with short black hair at the sides, thin-rimmed glasses, a thin moustache and shifty eyes; wears a dark grey suit, a light-grey shirt and a black tie, carrying a leather briefcase."),
    dict(id="raina", name="Raina", name_dhivehi="ރައިނާ",
         role="Rafhaan and Layaali's daughter, two years old",
         gender="female", age="2 years old",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="chubby cheeks, big bright brown eyes, sweet smile",
         hair="short soft curly dark hair with a small pink clip",
         build="toddler",
         default_outfit="soft pink long-sleeved toddler dress with white leggings",
         distinguishing_features="pink dress, curly hair",
         personality_cues="giggly, playful",
         visual_prompt="Raina: a two-year-old Maldivian toddler girl with light-brown skin, chubby cheeks, big bright brown eyes and short soft curly dark hair with a small pink clip; wears a soft pink long-sleeved toddler dress with white leggings."),
    dict(id="doctor", name="Doctor (unnamed)", name_dhivehi="ޑޮކްޓަރު",
         role="senior doctor at ADK Hospital in Malé",
         gender="male", age="late 40s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="calm face, neat short greying beard, kind serious eyes",
         hair="short black hair greying at the temples",
         build="medium build",
         default_outfit="white doctor's coat over a light-blue long-sleeved shirt, dark trousers, stethoscope around the neck",
         distinguishing_features="white coat, stethoscope",
         personality_cues="calm, serious, reassuring",
         visual_prompt="the doctor: a Maldivian man in his late 40s with medium-brown skin, short black hair greying at the temples and a neat short greying beard; wears a white doctor's coat over a light-blue long-sleeved shirt, dark trousers and a stethoscope around his neck."),
    dict(id="fake_nurse", name="Fake nurse (Raaya's hire)", name_dhivehi="ނަރުސް",
         role="woman disguised as a nurse, hired by Raaya to give Layaali a poisoned injection; caught by Rafhaan",
         gender="female", age="early 30s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="only nervous darting eyes visible above a pale-blue surgical mask",
         hair="covered by a white hijab",
         build="thin",
         default_outfit="white long-sleeved nurse tunic over loose white ankle-length trousers, white hijab fully covering hair and neck, pale-blue surgical face mask",
         distinguishing_features="surgical mask, nervous eyes",
         personality_cues="furtive, nervous",
         visual_prompt="the masked nurse: a thin Maldivian woman in her early 30s with medium-brown skin and nervous darting eyes above a pale-blue surgical face mask; wears a white long-sleeved nurse tunic over loose white ankle-length trousers and a white hijab fully covering her hair and neck."),
]

FIRST = dict(layaali=432, rafhaan=432, ahna=432, zoya=432, raaya=432, aminath=432, qaasim=432, khadeeja=434,
             zaahir=434, aasim=455, doctor=456, ibrahim=479, fake_nurse=480, shiyaz=481, raina=482, naasif=496)

if __name__ == "__main__":
    series_dir, episode = sys.argv[1], int(sys.argv[2])
    for c in CARDS:
        d = os.path.join(series_dir, "characters", c["id"])
        p = os.path.join(d, "card.json")
        if os.path.exists(p):
            print("reuse", c["id"]); continue
        os.makedirs(d, exist_ok=True)
        card = dict(c)
        card["first_seen_episode"] = FIRST.get(c["id"], episode)
        card["reference_from_cover"] = bool(c.get("reference_from_cover"))
        json.dump(card, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        print("new", c["id"])
