"""Series character cards for Hayaath. Creates card.json only for characters that don't exist yet."""
import json, os, sys

CARDS = [
    dict(id="hayaathu", name="Hayaathu", name_dhivehi="ހަޔާތު",
         role="protagonist, orphaned younger sister living with her uncle's family",
         gender="female", age="early 20s",
         ethnicity_look="Maldivian, South Asian features, warm light-brown skin",
         face="soft oval face, large dark expressive eyes with long lashes, thick dark arched eyebrows, straight nose, soft full lips",
         hair="fully covered by headscarf",
         build="slim, average height",
         default_outfit="loose long-sleeved ankle-length dress in dusty rose, soft blush-pink chiffon hijab fully covering hair and neck",
         distinguishing_features="resembles the heroine on the series cover",
         personality_cues="gentle, sad tearful eyes, often looking down",
         visual_prompt="Hayaathu: a Maldivian young woman in her early 20s with warm light-brown skin, soft oval face, large dark expressive eyes with long lashes, thick dark arched eyebrows, soft full lips, slim build; wears a loose long-sleeved ankle-length dusty-rose dress and a soft blush-pink chiffon hijab fully covering her hair and neck.",
         reference_from_cover=True),
    dict(id="dhooma", name="Dhooma", name_dhivehi="ދޫމާ",
         role="Hayaathu's elder sister, paralysed in the car accident that killed their parents 12 years ago; stutters when frightened",
         gender="female", age="late 20s",
         ethnicity_look="Maldivian, South Asian features, warm medium-brown skin",
         face="round gentle face, kind tired dark eyes, soft eyebrows, small nose",
         hair="fully covered by headscarf",
         build="slight, seated in a wheelchair",
         default_outfit="loose long-sleeved ankle-length dress in muted teal-green, cream cotton hijab, light grey knitted shawl over her lap; sits in a simple black manual wheelchair",
         distinguishing_features="always in a black manual wheelchair; legs do not move",
         personality_cues="calm, protective, warm small smile, eyes fill with tears easily",
         visual_prompt="Dhooma: a Maldivian woman in her late 20s with warm medium-brown skin, round gentle face, kind tired dark eyes, slight build; she sits in a simple black manual wheelchair; wears a loose long-sleeved ankle-length muted teal-green dress, a cream cotton hijab fully covering hair and neck, and a light grey knitted shawl over her lap."),
    dict(id="zoona", name="Zoona", name_dhivehi="ޒޫނާ",
         role="wife of uncle Waheed, careless and smug towards the sisters, sweet to her own daughter",
         gender="female", age="mid 40s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="round full face, arched pencilled eyebrows, light makeup, heavy-lidded bored eyes",
         hair="covered by a loosely draped black headscarf",
         build="plump, medium height",
         default_outfit="long-sleeved ankle-length maroon kaftan-style dress with a small printed pattern, black hijab draped over hair and neck",
         distinguishing_features="usually holding a smartphone",
         personality_cues="bored, dismissive, smirking",
         visual_prompt="Zoona: a plump Maldivian woman in her mid 40s with medium-brown skin, round full face, arched pencilled eyebrows, light makeup, heavy-lidded eyes; wears a long-sleeved ankle-length maroon kaftan-style dress with a small print and a black hijab covering her hair and neck; often holds a smartphone."),
    dict(id="areesha", name="Areesha", name_dhivehi="އަރީޝާ",
         role="Zoona and Waheed's daughter, Hayaathu's cousin; spoilt and mocking",
         gender="female", age="about 20",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="heart-shaped face, sharp winged eyeliner, glossy lips, high cheekbones, haughty look",
         hair="covered by headscarf",
         build="slim, tall",
         default_outfit="loose long-sleeved ankle-length mustard-yellow maxi dress, neatly styled beige satin hijab fully covering hair and neck",
         distinguishing_features="fashionable, well groomed",
         personality_cues="smug half smile, crossed arms, raised eyebrow",
         visual_prompt="Areesha: a slim tall Maldivian young woman about 20 with light-brown skin, heart-shaped face, high cheekbones, sharp winged eyeliner and glossy lips, haughty expression; wears a loose long-sleeved ankle-length mustard-yellow maxi dress and a neatly styled beige satin hijab fully covering her hair and neck."),
    dict(id="maaroof", name="Maaroof", name_dhivehi="މައުރޫފް",
         role="Hayaathu's beloved; working to meet her uncle's 3-million-rufiyaa condition",
         gender="male", age="late 20s",
         ethnicity_look="Maldivian, South Asian features, warm brown skin",
         face="strong jaw, well-groomed short dark beard, kind deep-set dark eyes, straight nose",
         hair="short dark wavy hair, neatly styled",
         build="tall, athletic",
         default_outfit="white long-sleeved button shirt, dark navy trousers",
         distinguishing_features="resembles the hero on the series cover",
         personality_cues="calm, protective, sincere",
         visual_prompt="Maaroof: a tall athletic Maldivian man in his late 20s with warm brown skin, short dark wavy hair, a well-groomed short dark beard, strong jaw and kind deep-set dark eyes; wears a white long-sleeved button shirt and dark navy trousers.",
         reference_from_cover=True),
    dict(id="young_driver", name="Fazaal", name_dhivehi="ފަޒާލް",
         role="handsome young man (~25) from Dubai staying at the big house; his car nearly hit the sisters (ep 272), he secretly rescued Hayaathu from the sea (ep 273); he is the 'Fazaal' Hayaathu is forced to marry, who sent his late brother Fawaz's photo instead of his own (ep 274)",
         aliases=["young driver (ep 272)", "the young man who rescued Hayaathu (ep 273)"],
         gender="male", age="about 25",
         ethnicity_look="Maldivian, South Asian features, light-brown skin",
         face="clean-shaven, sharp cheekbones, straight dark eyebrows, intense dark eyes",
         hair="short black hair swept back",
         build="tall, lean",
         default_outfit="black short-sleeved polo shirt, grey chinos, dark wristwatch",
         distinguishing_features="drives a dark grey sedan",
         personality_cues="frowning, intense, then thoughtful",
         visual_prompt="the young driver: a tall lean Maldivian man about 25 with light-brown skin, clean-shaven, sharp cheekbones, straight dark eyebrows, intense dark eyes and short black hair swept back; wears a black polo shirt, grey chinos and a dark wristwatch."),
    dict(id="waheed", name="Waheed", name_dhivehi="ވަހީދު",
         role="the sisters' paternal uncle (Bodubeybe) and guardian; controls their inheritance",
         gender="male", age="mid 50s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="heavy square face, deep frown lines, greying moustache, hard narrow eyes",
         hair="short greying hair",
         build="heavy-set",
         default_outfit="light grey long-sleeved button shirt, dark trousers",
         distinguishing_features="always stern",
         personality_cues="cold, controlling, arms crossed",
         visual_prompt="Waheed: a heavy-set Maldivian man in his mid 50s with medium-brown skin, heavy square face, deep frown lines, a greying moustache, short greying hair and hard narrow eyes; wears a light grey long-sleeved button shirt and dark trousers."),
    dict(id="hassan", name="Hassan", name_dhivehi="ހަސަން",
         role="Maaroof's close friend from the island; helps search the sea for Hayaathu",
         gender="male", age="late 20s",
         ethnicity_look="Maldivian, South Asian features, deep brown skin",
         face="round friendly face, short curly black hair, light stubble, broad nose, expressive eyebrows",
         hair="short curly black hair",
         build="stocky, medium height",
         default_outfit="faded olive-green crew-neck t-shirt, dark grey long trousers",
         distinguishing_features="stocky, curly hair",
         personality_cues="loyal, earnest, worried frown",
         visual_prompt="Hassan: a stocky Maldivian man in his late 20s with deep brown skin, a round friendly face, short curly black hair and light stubble; wears a faded olive-green crew-neck t-shirt and dark grey long trousers."),
    dict(id="asad", name="Asad", name_dhivehi="އަސަދު",
         role="islander who answered the phone call reporting Hayaathu was found; met leaving the mosque at dawn",
         gender="male", age="mid 30s",
         ethnicity_look="Maldivian, South Asian features, medium-brown skin",
         face="long face, neatly trimmed short black beard, cheerful eyes",
         hair="short black hair under a white knitted skullcap",
         build="lean, tall",
         default_outfit="white long-sleeved kurta-style shirt, dark checked sarong (feyli) to the ankles, white knitted skullcap",
         distinguishing_features="white skullcap, laughs easily",
         personality_cues="chatty, good-humoured",
         visual_prompt="Asad: a lean tall Maldivian man in his mid 30s with medium-brown skin, a long face, a neatly trimmed short black beard and cheerful eyes; wears a white knitted skullcap, a white long-sleeved kurta-style shirt and a dark checked sarong to the ankles."),
    dict(id="nurse", name="Nurse (unnamed)", name_dhivehi="ނަރުސްކުއްޖާ",
         role="young hospital nurse who cares for Hayaathu",
         gender="female", age="mid 20s",
         ethnicity_look="Maldivian, South Asian features, warm brown skin",
         face="round kind face, soft dark eyes, gentle smile",
         hair="fully covered by a white hijab",
         build="petite",
         default_outfit="light-blue long-sleeved nurse tunic over loose ankle-length light-blue trousers, white hijab fully covering hair and neck, small watch pinned to the tunic",
         distinguishing_features="light-blue nurse uniform",
         personality_cues="compassionate, calm",
         visual_prompt="the nurse: a petite Maldivian young woman in her mid 20s with warm brown skin, a round kind face and soft dark eyes; wears a light-blue long-sleeved nurse tunic over loose ankle-length light-blue trousers and a white hijab fully covering her hair and neck."),
    dict(id="yasir", name="Yasir", name_dhivehi="ޔާސިރު",
         role="Fazaal's close friend and go-between; attends the ring ceremony for him (ep 275), fetches Hayaathu to meet Fazaal and follows on his motorbike (ep 319); knows the truth about Fazaal's face",
         gender="male", age="about 26",
         ethnicity_look="Maldivian, South Asian features, warm brown skin",
         face="friendly oval face, rounded cheeks, a neatly trimmed thin moustache and light stubble, lively dark eyes behind black rectangular-framed glasses, easy knowing grin",
         hair="short black hair, cropped close at the sides, slightly spiky on top",
         build="medium height, solid average build",
         default_outfit="light-blue and white checked short-sleeved button shirt, khaki long trousers, brown sandals",
         distinguishing_features="black rectangular-framed glasses, checked shirt, usually on his phone; rides a motorbike",
         personality_cues="cheerful, teasing, relaxed, raised eyebrow, quick grin",
         visual_prompt="Yasir: a Maldivian man about 26 with warm brown skin, a friendly oval face with rounded cheeks, a thin neatly trimmed moustache and light stubble, lively dark eyes behind black rectangular-framed glasses, short black hair cropped close at the sides; medium height, average build; wears a light-blue and white checked short-sleeved button shirt and khaki long trousers."),
    dict(id='shafeena', name='Shafeena', name_dhivehi='ޝަފީނާ', role="the sisters' beloved aunt (bodudhaitha), their late father's full younger sister; kind and protective, arrives to find Hayaathu hurt (ep 415)", gender='female', age='late 40s', ethnicity_look='Maldivian, South Asian features, warm medium-brown skin', face='oval motherly face, soft laugh lines, warm worried dark eyes, gentle eyebrows, no makeup', hair='fully covered by headscarf', build='medium height, slightly plump', default_outfit='loose long-sleeved ankle-length plum-purple dress, plain off-white cotton hijab fully covering hair and neck, a small black handbag over her shoulder', distinguishing_features='plum-purple dress with off-white hijab; motherly presence', personality_cues='warm, caring, alarmed concern, protective', visual_prompt='Shafeena: a slightly plump Maldivian woman in her late 40s with warm medium-brown skin, an oval motherly face with soft laugh lines and warm dark eyes; wears a loose long-sleeved ankle-length plum-purple dress and a plain off-white cotton hijab fully covering her hair and neck, a small black handbag over her shoulder.'),
]

if __name__ == "__main__":
    series_dir, episode = sys.argv[1], int(sys.argv[2])
    for c in CARDS:
        d = os.path.join(series_dir, "characters", c["id"])
        p = os.path.join(d, "card.json")
        if os.path.exists(p):
            print("reuse", c["id"]); continue
        os.makedirs(d, exist_ok=True)
        card = {k: v for k, v in c.items() if k != "reference_from_cover"}
        card["first_seen_episode"] = episode
        card["reference_from_cover"] = bool(c.get("reference_from_cover"))
        json.dump(card, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        print("new", c["id"])
