"""Series character cards for Milahanduvaru (a moonlit island-village story of a widower, sorcery and a jinn wife).
Creates card.json only for characters that don't exist yet.
Usage: python characters_milahanduvaru.py <series_dir> <first_episode>
"""
import json, os, sys

MV = "Maldivian, South Asian features, warm brown skin"
CARDS = [
    dict(id="shamaan", name="Shamaan", name_dhivehi="ޝަމްއާން",
         role="protagonist; young widower (first wife Zihuna died suddenly, sorcery suspected), father of little Yameen, office worker; later marries the mysterious Zumra",
         gender="male", age="about 28",
         ethnicity_look=MV,
         face="lean oval face, soft dark brown eyes with a sad, tired look, straight dark eyebrows, short neatly trimmed black beard and moustache",
         hair="short black hair, slightly wavy, neatly combed",
         build="slim, average height",
         default_outfit="plain light-blue long-sleeved button shirt with sleeves rolled to the forearm, dark grey long trousers",
         distinguishing_features="short trimmed beard, light-blue shirt",
         personality_cues="gentle, grieving, devoted father; later lovestruck, anxious, hot-tempered when his wife is accused",
         visual_prompt="Shamaan: a slim Maldivian man about 28 with warm brown skin, a lean oval face, soft dark brown eyes with a sad tired look, straight dark eyebrows, short slightly wavy neatly combed black hair and a short neatly trimmed black beard; wears a plain light-blue long-sleeved button shirt with sleeves rolled to the forearm and dark grey long trousers."),
    dict(id="yameen", name="Yameen", name_dhivehi="ޔަމީން",
         role="Shamaan and the late Zihuna's little son; troubled by an unseen presence (later revealed as his jinn half-sister Nazaaha)",
         gender="male", age="about 2",
         ethnicity_look=MV,
         face="round chubby toddler face, big dark innocent eyes, small nose",
         hair="soft short black curly hair",
         build="small toddler",
         default_outfit="small mustard-yellow short-sleeved t-shirt and light-grey long cotton pants",
         distinguishing_features="mustard-yellow t-shirt, curly hair",
         personality_cues="clingy, cries for his father, giggles at empty corners",
         visual_prompt="Yameen: a small Maldivian toddler boy about 2 years old with warm brown skin, a round chubby face, big dark innocent eyes and soft short black curly hair; wears a small mustard-yellow short-sleeved t-shirt and light-grey long cotton pants."),
    dict(id="sakeena", name="Sakeena", name_dhivehi="ސަކީނާ",
         role="Shamaan's mother, Yameen's grandmother; caring, devout, protective; suspicious of Zumra",
         gender="female", age="mid 50s",
         ethnicity_look=MV,
         face="round kind face with soft wrinkles, worried dark eyes, small nose",
         hair="covered by headscarf",
         build="short, plump",
         default_outfit="loose long-sleeved ankle-length maroon traditional Maldivian dress (libaas) with a thin gold-thread neckline band, and a soft beige headscarf fully covering her hair and neck",
         distinguishing_features="maroon libaas, beige headscarf",
         personality_cues="warm, tearful, fierce when her family is threatened",
         visual_prompt="Sakeena: a short plump Maldivian woman in her mid 50s with warm brown skin, a round kind face with soft wrinkles and worried dark eyes; wears a loose long-sleeved ankle-length maroon traditional Maldivian dress with a thin gold-thread neckline band and a soft beige headscarf fully covering her hair and neck."),
    dict(id="shamaan_father", name="Shamaan's father", name_dhivehi="ބައްޕަ",
         role="Shamaan's father, Sakeena's husband, a fisherman; often unwell (fever, later treatment in Malé); Naasira is his eldest sister",
         gender="male", age="about 60",
         ethnicity_look=MV,
         face="weathered lined face, deep-set tired eyes, short grey-white beard",
         hair="short grey hair under a white knitted skullcap",
         build="lean, wiry, slightly stooped",
         default_outfit="white knitted skullcap, faded olive-green long-sleeved collared shirt and a dark checked sarong (feyli) to the ankles",
         distinguishing_features="white skullcap, grey-white beard, checked sarong",
         personality_cues="quiet, weary, sighs often; protective",
         visual_prompt="Shamaan's father: a lean wiry slightly stooped Maldivian man about 60 with weathered warm brown skin, a lined face, deep-set tired eyes and a short grey-white beard; wears a white knitted skullcap, a faded olive-green long-sleeved collared shirt and a dark checked sarong to the ankles."),
    dict(id="zihuna", name="Zihuna", name_dhivehi="ޒިހުނާ",
         role="Shamaan's late first wife, Yameen's mother; died suddenly about two years into the marriage; seen only in a framed photo or soft memories",
         gender="female", age="early 20s",
         ethnicity_look=MV,
         face="gentle oval face, warm shy smile, large dark eyes",
         hair="covered by hijab",
         build="slim",
         default_outfit="loose long-sleeved ankle-length soft lilac dress and a pale pink hijab fully covering her hair and neck",
         distinguishing_features="pale pink hijab, shy smile",
         personality_cues="quiet, gentle, kind",
         visual_prompt="Zihuna: a slim Maldivian young woman in her early 20s with warm brown skin, a gentle oval face, large dark eyes and a warm shy smile; wears a loose long-sleeved ankle-length soft lilac dress and a pale pink hijab fully covering her hair and neck."),
    dict(id="zumra", name="Zumra", name_dhivehi="ޒުމްރާ",
         role="mysterious beautiful young woman who appears only at night, 'from Malé'; becomes Shamaan's second wife; a jinn",
         gender="female", age="early 20s",
         ethnicity_look="Maldivian, South Asian features, smooth light-brown skin with a faint pale moonlit glow",
         face="strikingly beautiful heart-shaped face, large dark eyes with an unusual silvery sparkle, enigmatic faint smile",
         hair="covered by hijab",
         build="slim, graceful, upright",
         default_outfit="loose long-sleeved ankle-length midnight-blue dress with fine silver embroidery at the cuffs and hem, and a pale silver-grey hijab fully covering her hair and neck; carries a small cloth shoulder bag",
         distinguishing_features="silvery sparkle in her eyes, midnight-blue dress, silver-grey hijab; dresses unlike the island girls",
         personality_cues="playful, confident, mysterious; sudden moods",
         visual_prompt="Zumra: a slim graceful Maldivian young woman in her early 20s with smooth light-brown skin with a faint moonlit glow, a strikingly beautiful heart-shaped face, large dark eyes with an unusual silvery sparkle and an enigmatic faint smile; wears a loose long-sleeved ankle-length midnight-blue dress with fine silver embroidery at the cuffs and hem and a pale silver-grey hijab fully covering her hair and neck."),
    dict(id="akram", name="Akram", name_dhivehi="އަކްރަމް",
         role="Shamaan's best friend; loud, playful, likes the shows and the girls; cannot see Zumra",
         gender="male", age="about 28",
         ethnicity_look=MV,
         face="round cheerful face, broad grin, thick eyebrows, clean-shaven",
         hair="short black hair with a slightly spiky top",
         build="stocky, medium height",
         default_outfit="red-and-navy checked short-sleeved shirt over a white t-shirt, beige long trousers",
         distinguishing_features="red-and-navy checked shirt, broad grin",
         personality_cues="teasing, restless, secretly scared",
         visual_prompt="Akram: a stocky Maldivian man about 28 with warm brown skin, a round cheerful clean-shaven face, a broad grin, thick eyebrows and short black hair with a slightly spiky top; wears a red-and-navy checked short-sleeved shirt over a white t-shirt and beige long trousers."),
    dict(id="hassanfulhu", name="Hassanfulhu", name_dhivehi="ހަސަންފުޅު",
         role="the atoll's most famous fanditha-man / reciter from another island, hired to drive the jinn from the island; leads night recitations (kiyevelli)",
         gender="male", age="about 65",
         ethnicity_look=MV,
         face="long calm stern face, sharp steady eyes, long white beard, deep lines",
         hair="covered by a white skullcap",
         build="tall, lean, upright",
         default_outfit="white knitted skullcap, white long-sleeved shirt and a white sarong (mundu) to the ankles; often holds a closed book",
         distinguishing_features="all in white, long white beard",
         personality_cues="calm, stubborn, unafraid",
         visual_prompt="Hassanfulhu: a tall lean upright Maldivian man about 65 with weathered warm brown skin, a long calm stern face, sharp steady eyes and a long white beard; wears a white knitted skullcap, a white long-sleeved shirt and a white sarong to the ankles."),
    dict(id="sattar", name="Sattar", name_dhivehi="ސައްތާރު",
         role="strong young islander among the 40 men at the recitations; names Shamaan's wife as the jinn; dies after meeting the jinn in the rain",
         gender="male", age="mid 20s",
         ethnicity_look=MV,
         face="square jaw, wide-set eyes, thin moustache",
         hair="short cropped black hair",
         build="broad-shouldered, muscular",
         default_outfit="dark green short-sleeved t-shirt and a brown checked sarong",
         distinguishing_features="broad shoulders, dark green t-shirt",
         personality_cues="bold, then terrified",
         visual_prompt="Sattar: a broad-shouldered muscular Maldivian young man in his mid 20s with warm brown skin, a square jaw, wide-set eyes, a thin moustache and short cropped black hair; wears a dark green short-sleeved t-shirt and a brown checked sarong."),
    dict(id="ahmadhufulhu", name="Ahmadhufulhu", name_dhivehi="އަޙްމަދުފުޅު",
         role="Zumra's father; 'lives in Singapore', owns a nearby uninhabited island; tall and powerful; rumoured to walk on the sea (a jinn)",
         gender="male", age="about 60",
         ethnicity_look="Maldivian, South Asian features, deep brown skin",
         face="broad stern face, heavy brows, piercing dark eyes, thick grey beard",
         hair="short grey hair",
         build="very tall, huge, powerful",
         default_outfit="long dark charcoal kurta with a high collar down to the shins over dark trousers",
         distinguishing_features="unusually tall and massive, charcoal kurta",
         personality_cues="formal, guarded, imposing",
         visual_prompt="Ahmadhufulhu: a very tall, huge and powerful Maldivian man about 60 with deep brown skin, a broad stern face, heavy brows, piercing dark eyes, short grey hair and a thick grey beard; wears a long dark charcoal high-collared kurta down to the shins over dark trousers."),
    dict(id="nazaaha", name="Nazaaha", name_dhivehi="ނަޒާހާ",
         role="the jinn daughter of Shamaan and Zumra; appears on moonlit nights; was Yameen's 'imaginary friend'",
         gender="female", age="about 6",
         ethnicity_look="Maldivian, South Asian features, smooth light-brown skin with a faint pale moonlit glow",
         face="small round face, big dark eyes with a faint silvery sparkle like her mother's, innocent smile",
         hair="covered by a small headscarf",
         build="small child",
         default_outfit="loose long-sleeved ankle-length small midnight-blue dress and a small pale silver-grey headscarf covering her hair",
         distinguishing_features="looks like a small Zumra; silvery sparkle in her eyes",
         personality_cues="shy, grieving, sweet",
         visual_prompt="Nazaaha: a small Maldivian girl about 6 years old with smooth light-brown skin with a faint moonlit glow, a small round face, big dark eyes with a faint silvery sparkle and an innocent smile; wears a loose long-sleeved ankle-length small midnight-blue dress and a small pale silver-grey headscarf covering her hair."),
]

FIRST = dict(shamaan=252, yameen=252, sakeena=252, shamaan_father=252, zihuna=252, zumra=254, akram=254,
             hassanfulhu=257, sattar=257, ahmadhufulhu=256, nazaaha=260)

if __name__ == "__main__":
    series_dir, episode = sys.argv[1], int(sys.argv[2])
    for c in CARDS:
        d = os.path.join(series_dir, "characters", c["id"])
        p = os.path.join(d, "card.json")
        if os.path.exists(p):
            continue
        os.makedirs(d, exist_ok=True)
        card = dict(c)
        card["first_seen_episode"] = FIRST.get(c["id"], episode)
        card["reference_from_cover"] = bool(c.get("reference_from_cover"))
        json.dump(card, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        print("new", c["id"])
