"""Series character cards for Taubaa (an anthology of repentance stories: each episode has its own cast).
Creates card.json only for characters that don't exist yet.
Usage: python characters_taubaa.py <series_dir> <first_episode>
"""
import json, os, sys

SAUDI = "Saudi Arab, Middle Eastern features, warm olive-tan skin"
CARDS = [
    # ---- ep 287: the son who smashed the TV, and his praying mother (setting: a simple Maldivian home)
    dict(id="tv_son", name="the son", name_dhivehi="ދަރިފުޅު",
         role="ep 287: only son of an old widow; spends his nights watching films and dramas, mocks his mother's advice to pray; later repents",
         gender="male", age="early 20s",
         ethnicity_look="Maldivian, South Asian features, warm brown skin",
         face="lean face, dark tired eyes with shadows under them, thin moustache and light stubble, straight thick eyebrows",
         hair="short messy black hair",
         build="slim, average height",
         default_outfit="faded charcoal-grey long-sleeved t-shirt and dark navy track trousers",
         distinguishing_features="sleepy, screen-lit face at night",
         personality_cues="careless, dismissive at first; later remorseful and gentle",
         visual_prompt="The son: a slim Maldivian young man in his early 20s with warm brown skin, short messy black hair, a lean face, dark tired eyes with shadows under them, straight thick eyebrows, a thin moustache and light stubble; wears a faded charcoal-grey long-sleeved t-shirt and dark navy track trousers."),
    dict(id="devout_mother", name="the mother", name_dhivehi="މުސްކުޅި މަންމަ",
         role="ep 287: frail elderly widowed mother who prays every night in the last third of the night for her son's guidance",
         gender="female", age="about 70",
         ethnicity_look="Maldivian, South Asian features, warm brown skin",
         face="thin wrinkled kind face, gentle sad eyes, soft deep lines",
         hair="covered by headscarf",
         build="small, thin, slightly stooped",
         default_outfit="loose long-sleeved ankle-length faded sea-green traditional Maldivian dress (libaas) and a plain white cotton prayer headscarf fully covering her hair and neck",
         distinguishing_features="white prayer headscarf, frail hands",
         personality_cues="patient, tearful, prayerful, loving",
         visual_prompt="The mother: a small thin slightly stooped Maldivian woman about 70 with warm brown skin, a thin wrinkled kind face and gentle sad eyes; wears a loose long-sleeved ankle-length faded sea-green traditional Maldivian dress and a plain white cotton headscarf fully covering her hair and neck."),
    # ---- ep 298: Jawad, a Saudi man who lived a sinful life abroad
    dict(id="jawad", name="Jawad", name_dhivehi="ޖަވާދު",
         role="ep 298: Saudi man who travelled through Greece, France, Holland, Canada and America living in sin; studied in America; married a pious woman; repents in his car on the way to work after hearing a recorded Quran recitation and dua",
         gender="male", age="early 30s",
         ethnicity_look=SAUDI,
         face="handsome angular face, short neatly trimmed black beard, deep-set dark brown eyes, strong eyebrows",
         hair="short black hair, neatly styled",
         build="tall, athletic",
         default_outfit="dark navy zip jacket over a plain grey crew-neck shirt, dark long trousers (abroad); in Saudi Arabia a white thobe",
         distinguishing_features="trimmed black beard",
         personality_cues="restless, inwardly torn; later humble and tearful",
         visual_prompt="Jawad: a tall athletic Saudi Arab man in his early 30s with warm olive-tan skin, short neatly styled black hair, a short neatly trimmed black beard, deep-set dark brown eyes and strong eyebrows; wears a dark navy zip jacket over a plain grey crew-neck shirt and dark long trousers."),
    dict(id="jawad_wife", name="Jawad's wife", name_dhivehi="އަނބިމީހާ",
         role="ep 298: kind, righteous, religious woman from a pious family; Jawad's wife",
         gender="female", age="late 20s",
         ethnicity_look=SAUDI,
         face="gentle oval face, kind dark eyes, soft features, no makeup",
         hair="fully covered by hijab",
         build="slim, average height",
         default_outfit="loose ankle-length black abaya with subtle dark embroidery at the cuffs and a dusty-rose hijab fully covering hair and neck",
         distinguishing_features="dusty-rose hijab",
         personality_cues="calm, trusting, quietly prayerful",
         visual_prompt="Jawad's wife: a slim Saudi Arab woman in her late 20s with warm olive-tan skin, a gentle oval face, kind dark eyes and soft features; wears a loose ankle-length black abaya with subtle dark embroidery at the cuffs and a dusty-rose hijab fully covering her hair and neck."),
    # ---- ep 299: a young man of Riyadh ruined by bad friends and drugs, who repents after nearly dying
    dict(id="riyadh_boy", name="the boy (narrator, age 14-17)", name_dhivehi="ޒުވާނާ (ކުޑައިރު)",
         role="ep 299: the narrator as a schoolboy in Riyadh, son of a very religious father; trapped by bad friends during exams",
         gender="male", age="14-15",
         ethnicity_look=SAUDI,
         face="boyish round face, big dark eyes, smooth chin, slight dark fuzz on upper lip",
         hair="short black hair",
         build="slim teenage build",
         default_outfit="plain white thobe, no headdress",
         distinguishing_features="young teen, white thobe",
         personality_cues="naive, eager, later exhausted and hollow-eyed",
         visual_prompt="The boy: a slim Saudi Arab teenage boy of about 14 with warm olive-tan skin, a boyish round face, big dark eyes and short black hair; wears a plain white thobe and no headdress."),
    dict(id="riyadh_man", name="the young man (narrator, age 18-22)", name_dhivehi="ޒުވާނާ",
         role="ep 299: the narrator as a young man; years of addiction, a crash, a near-death night, then repentance and umrah",
         gender="male", age="about 20",
         ethnicity_look=SAUDI,
         face="gaunt narrow face, hollow cheeks, dark circles under dark eyes, patchy short black beard",
         hair="short untidy black hair",
         build="thin, wiry",
         default_outfit="rumpled off-white thobe, no headdress",
         distinguishing_features="gaunt, hollow-eyed, patchy beard",
         personality_cues="lost, shaky, fearful; after repentance calm and clear-eyed",
         visual_prompt="The young man: a thin wiry Saudi Arab man about 20 with warm olive-tan skin, a gaunt narrow face with hollow cheeks, dark circles under his dark eyes, short untidy black hair and a patchy short black beard; wears a rumpled off-white thobe and no headdress."),
    dict(id="pious_father", name="the father", name_dhivehi="ބައްޕަ",
         role="ep 299: the narrator's very religious father in Riyadh; allows no entertainment devices at home; visits his son in the clinic and leaves in silent grief",
         gender="male", age="mid 60s",
         ethnicity_look=SAUDI,
         face="dignified lined face, long white beard, grave kind eyes",
         hair="covered by headdress",
         build="tall, upright, lean",
         default_outfit="white thobe, red-and-white checked shemagh headdress with black agal cord, brown bisht cloak over the shoulders",
         distinguishing_features="long white beard, red-checked shemagh",
         personality_cues="grave, devout, silent sorrow",
         visual_prompt="The father: a tall upright lean Saudi Arab man in his mid 60s with warm olive-tan skin, a dignified lined face, a long white beard and grave kind eyes; wears a white thobe, a red-and-white checked shemagh headdress with a black agal cord and a brown bisht cloak over his shoulders."),
    dict(id="elder_brother", name="the elder brother", name_dhivehi="ބޮޑުބޭބެ",
         role="ep 299: the narrator's eldest brother who lives with his family in another town and helps him finish school",
         gender="male", age="early 40s",
         ethnicity_look=SAUDI,
         face="broad calm face, full black beard with a few grey strands, kind worried eyes",
         hair="covered by headdress",
         build="sturdy, medium height",
         default_outfit="white thobe and plain white ghutra headdress",
         distinguishing_features="full black beard, white ghutra",
         personality_cues="protective, alarmed, caring",
         visual_prompt="The elder brother: a sturdy Saudi Arab man in his early 40s with warm olive-tan skin, a broad calm face, a full black beard with a few grey strands and kind worried eyes; wears a white thobe and a plain white ghutra headdress."),
    dict(id="nephew", name="the nephew", name_dhivehi="ބޮޑުބޭބެގެ ދަރިއަކު",
         role="ep 299: the elder brother's grown son who drives the narrator to a private clinic",
         gender="male", age="about 19",
         ethnicity_look=SAUDI,
         face="youthful lean face, light black moustache, alert dark eyes",
         hair="short black hair",
         build="slim, tall",
         default_outfit="light-grey thobe, no headdress",
         distinguishing_features="light-grey thobe",
         personality_cues="anxious, dutiful",
         visual_prompt="The nephew: a slim tall Saudi Arab young man about 19 with warm olive-tan skin, a youthful lean face, short black hair, a light black moustache and alert dark eyes; wears a light-grey thobe and no headdress."),
    dict(id="clinic_doctor", name="the clinic doctor", name_dhivehi="ޑޮކްޓަރު",
         role="ep 299: doctor at a private clinic who at first refuses, then treats the narrator and warns him",
         gender="male", age="about 50",
         ethnicity_look="Arab, Middle Eastern features, light olive skin",
         face="serious face, short grey-flecked beard, rimless glasses",
         hair="short receding grey-black hair",
         build="medium build",
         default_outfit="white doctor's coat over a pale blue shirt and dark trousers, stethoscope around the neck",
         distinguishing_features="rimless glasses, stethoscope",
         personality_cues="stern, then grudgingly helpful",
         visual_prompt="The clinic doctor: an Arab man about 50 with light olive skin, a serious face, a short grey-flecked beard, rimless glasses and short receding grey-black hair; wears a white doctor's coat over a pale blue shirt and dark trousers, with a stethoscope around his neck."),
    dict(id="righteous_friend", name="the righteous young man", name_dhivehi="ޞާލިޙު ޒުވާނާ",
         role="ep 299: a pious young man who rescues the narrator from his bad company and takes him to Makkah for umrah",
         gender="male", age="mid 20s",
         ethnicity_look=SAUDI,
         face="bright serene face, neat medium black beard, warm smiling eyes",
         hair="covered by headdress",
         build="average build",
         default_outfit="spotless white thobe and white ghutra headdress",
         distinguishing_features="serene smile, neat beard",
         personality_cues="gentle, kind, steady",
         visual_prompt="The righteous young man: a Saudi Arab man in his mid 20s with warm olive-tan skin, a bright serene face, a neat medium black beard and warm smiling eyes; wears a spotless white thobe and a white ghutra headdress."),
]

FIRST = dict(tv_son=287, devout_mother=287, jawad=298, jawad_wife=298)

if __name__ == "__main__":
    series_dir, episode = sys.argv[1], int(sys.argv[2])
    for c in CARDS:
        d = os.path.join(series_dir, "characters", c["id"])
        p = os.path.join(d, "card.json")
        if os.path.exists(p):
            continue
        os.makedirs(d, exist_ok=True)
        card = dict(c)
        card["first_seen_episode"] = FIRST.get(c["id"], episode)
        card["reference_from_cover"] = bool(c.get("reference_from_cover"))
        json.dump(card, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
        print("new", c["id"])
