"""Shot plan for Hayaath episode 272. Merges with work/segments.json -> scenes.json."""
import json, sys

LOC = {
    "bedroom": "small plain bedroom in an old Maldivian coral-stone house at night, single bed with a simple cotton sheet, wooden louvered window, ceiling fan, dim warm lamp light",
    "living": "modest Maldivian house living room at night, cushioned sofa, patterned floor tiles, ceiling fan, warm overhead light, bedroom doors along one wall",
    "street": "narrow island town street at night in the Maldives, warm streetlights, low walled houses, coconut palms, parked motorbikes",
    "road": "wide busy island main road at night in the Maldives, streetlights, fast cars and motorbikes with headlight streaks",
    "memory": "a rainy night road twelve years ago, hazy desaturated memory",
    "beach": "secluded beach on the quiet side of a Maldivian island at night, a paved path ending at white sand, palm trees, moonlit lagoon, waves breaking white on the distant reef",
    "house_other": "inside the uncle's house at night, plain walls, dim light",
}

# (english, characters, loc, visual, camera, image, sensitive, safe, ambience, sfx[(name, word, gainDb)], extras)
S = [
 ("The light of the twinkling stars is seen by every eye in the world. But who ever sees the darkness that surrounds those stars?",
  [], "beach", "a vast night sky full of twinkling stars above a dark lagoon, silhouettes of coconut palms and a coral-stone house roofline, deep blue darkness around the stars",
  "wide establishing shot, low angle", None, None, None, "night_exterior", [], {}),
 ("As soon as she got home she sat in a corner of her bed, head on her knees, sobbing. She kept thinking it would have been better if she had not come home today.",
  ["hayaathu"], "bedroom", "Hayaathu sitting curled in the corner of her bed, knees drawn up, forehead resting on her knees, face hidden, shoulders hunched, lonely",
  "medium wide, slightly high angle", None, None, None, "room_night", [("sob_breath", "ގިސްލާ", -24)], {}),
 ("Why did something this big have to befall her? Is her crime that she breathes in this world?",
  ["hayaathu"], "bedroom", "Hayaathu lifting her face slightly from her knees, wet eyelashes, a tear on her cheek, staring into nothing, lamp light on one side of her face",
  "close-up, eye level", None, None, None, "room_night", [], {"hum": True}),
 ("Is it her fault that her father and mother left this world? Why must she always hear that?",
  ["hayaathu"], "bedroom", "on a small wooden shelf an old framed family photograph of a smiling couple with two little girls, faces softly out of focus; Hayaathu's hand in a rose sleeve gently touching the frame",
  "close-up on the photo frame, shallow focus", None, None, None, "room_night", [], {}),
 ("Why does the world keep forcing her? A question. Again a question. So many questions. Where is the answer?",
  ["hayaathu"], "bedroom", "Hayaathu standing at the wooden louvered window, looking out at the moon through the slats, moonlight striping her face, pensive",
  "medium shot from the side", None, None, None, "room_night", [], {}),
 ("Today she wanted to cry until her heart was emptied, to sob out loud. But even that is a crime. Even tears in her eyes are a crime to the people of that house.",
  ["hayaathu"], "bedroom", "Hayaathu pressing her hand over her mouth to muffle her sobs, eyes squeezed shut, tears, sitting on the edge of the bed",
  "medium close-up", None, None, None, "room_night", [("sob_breath", "ގިސްލާ", -24)], {"hum": True}),
 ("With the pain in her heart, tears kept streaming. Since her parents left this world her tears have never had a chance to dry.",
  ["hayaathu"], "bedroom", "extreme close-up of Hayaathu's large dark eye brimming with tears, a single tear rolling down her cheek, warm lamp glow",
  "extreme close-up", None, None, None, "room_night", [], {}),
 ("The door opened and a wheelchair rolled in. At the sound Hayaathu lifted her head from her knees. Through her tears everything before her was blurred.",
  ["dhooma"], "bedroom", "the bedroom door opening, Dhooma in her wheelchair rolling in through the doorway, backlit by the corridor light, seen softly blurred as if through tears",
  "point of view from the bed, soft focus", None, None, None, "room_night", [("door_open", "ދޮރުހުޅުވާލާފައި", -16), ("wheelchair_roll", "ވީލް", -20)], {}),
 ("Seeing her, she cried even harder, got up from the bed and hugged her. 'Dhontha...' Hayaathu sobbed.",
  ["hayaathu", "dhooma"], "bedroom", "Hayaathu bending down to hug her sister Dhooma who sits in her wheelchair, Hayaathu's face buried on her sister's shoulder, Dhooma's eyes closed in compassion; two sisters",
  "medium shot", None, None, None, "room_night", [("cloth_rustle", "ތެދުވެގެން", -22), ("sob_breath", "ގިސްލަމުން", -24)], {}),
 ("'What happened, why are you crying again today? Who said what?' Dhooma asked tenderly. 'Areesha...' Hayaathu sobbed.",
  ["dhooma"], "bedroom", "Dhooma in her wheelchair looking up with gentle worried eyes, her hand raised to comfort her sister just out of frame",
  "close-up, slightly high angle", None, None, None, "room_night", [], {}),
 ("'Did Areesha insult you on purpose again today?' Dhooma asked, gently rubbing her back. Hayaathu pulled away from Dhooma.",
  ["hayaathu", "dhooma"], "bedroom", "Hayaathu stepping back from Dhooma's wheelchair, turning her face away, Dhooma reaching out with concern",
  "medium wide", None, None, None, "room_night", [], {}),
 ("And wiped the tears from her eyes. Right now she did not want to pour out the complaints in her heart to Dhooma.",
  ["hayaathu"], "bedroom", "Hayaathu wiping the tears from her eyes with the back of her hand, lips pressed together, holding everything in",
  "close-up", None, None, None, "room_night", [], {}),
 ("Wiping her tears she held the wheelchair handles and pushed it forward. As they came out of the room, Zoona, her uncle's wife, was sitting playing a game on her phone.",
  ["zoona", "hayaathu", "dhooma"], "living", "Zoona lounging on the sofa engrossed in a game on her smartphone in the foreground; in the background Hayaathu pushes Dhooma's wheelchair out of a bedroom doorway",
  "wide shot, deep focus", None, None, None, "living_night", [("wheelchair_roll", "ދުއްވާލިއެވެ", -20), ("phone_game_taps", "ފޯނުން", -26)], {}),
 ("Seeing the two she asked carelessly. 'Where are you off to this late?' Zoona asked in a bored voice.",
  ["zoona"], "living", "Zoona glancing up from her phone with a bored, dismissive expression, one eyebrow raised, phone screen glow on her face",
  "medium close-up", None, None, None, "living_night", [], {}),
 ("'Just outside to cool off a little,' Dhooma replied. 'Yes, go wherever you can now. Once Hayaathu leaves, Dhooma won't be going anywhere.'",
  ["dhooma", "hayaathu"], "living", "Dhooma in her wheelchair answering politely with a small smile, Hayaathu standing behind her holding the handles, eyes red",
  "medium shot", None, None, None, "living_night", [], {}),
 ("Zoona said, looking at Hayaathu's face, red from crying. Dhooma didn't understand what Zoona meant. But Hayaathu understood.",
  ["hayaathu"], "living", "Hayaathu's face with red swollen eyes, frozen as she realises the cruel meaning of the words, hurt and humiliation",
  "close-up", None, None, None, "living_night", [], {"hum": True}),
 ("'Mum, where are the earrings I brought yesterday?' Areesha asked, opening her room door.",
  ["areesha"], "living", "Areesha opening a bedroom door and stepping half out, one hand on the door handle, looking towards her mother",
  "medium shot", None, None, None, "living_night", [("door_open", "ހުޅުވަލަމުން", -16)], {}),
 ("'Darling, Mum doesn't know, it'll be wherever you put it, have a look,' Zoona said sweetly and lovingly.",
  ["zoona"], "living", "Zoona smiling sweetly and warmly towards her daughter off-screen, phone resting in her lap",
  "medium close-up", None, None, None, "living_night", [], {}),
 ("'So Hayaathu, how do you like the surprise I gave you?' Areesha asked mockingly. 'Don't comment on other people's private matters again,'",
  ["areesha"], "living", "Areesha leaning on the door frame with arms crossed, a smug mocking smirk, raised eyebrow",
  "medium close-up, low angle", None, None, None, "living_night", [], {}),
 ("'Forget Maaroof, he's not meant for you, stop hoping for impossible things. Hurry and get ready to go to the Beast,'",
  ["hayaathu", "dhooma", "areesha"], "living", "Hayaathu standing still behind Dhooma's wheelchair with Dhooma seated in it, Hayaathu's eyes lowered, wounded, her hands on the wheelchair handles; Areesha blurred in the foreground looking at her",
  "over-the-shoulder, shallow focus", None, None, None, "living_night", [], {"hum": True}),
 ("'you're Beauty, after all.' Areesha said with a mocking half-smile. 'Areesha, what kind of talk is this? Go inside.'",
  ["areesha"], "living", "close-up of Areesha's cruel half-smile, glossy lips, eyes narrowed with amusement",
  "close-up", None, None, None, "living_night", [], {}),
 ("Zoona said. Though she said that to Areesha, a mocking smile showed on her own lips too.",
  ["zoona"], "living", "Zoona with a thin suppressed smirk at the corner of her lips, eyes sliding sideways",
  "close-up", None, None, None, "living_night", [], {}),
 ("'Don't just stand there, go wherever you're going and come back. If your uncle finds out you went out, he'll shout at me,' Zoona said, rolling her eyes.",
  ["zoona"], "living", "(reuse) Zoona bored and dismissive", "medium close-up", "shot_014", None, None, "living_night", [], {}),
 ("Not wanting to hear any more of their talk, Hayaathu went out with Dhooma.",
  ["hayaathu", "dhooma"], "street", "the front door of the house open onto the night street, Hayaathu pushing Dhooma's wheelchair out through the gate, seen from behind",
  "wide shot from behind", None, None, None, "street_night", [("door_close", "ނިކުތެވެ", -18)], {}),
 ("She walked on with sorrow and complaints in her heart. Her tear-filled eyes searched for a glimmer of hope.",
  ["hayaathu", "dhooma"], "street", "Hayaathu pushing Dhooma's wheelchair along a quiet night street under warm streetlights, long shadows, the moon above the palms",
  "wide tracking shot from behind", None, None, None, "street_night", [("footsteps_pavement", "ފިޔަވަޅު", -22)], {}),
 ("She pushed the wheelchair along the roadside hoping to reach some peace. Lost in thought, Hayaathu tried to cross the road.",
  ["hayaathu", "dhooma"], "road", "side view of Hayaathu with a distant absent gaze pushing Dhooma's wheelchair off the curb onto a wide road at night",
  "medium wide, side view", None, None, None, "road_busy", [("wheelchair_roll", "ދުއްވަމުން", -20)], {}),
 ("It was a road where vehicles sped, and they kept racing past without a break.",
  [], "road", "a wide island road at night with cars and motorbikes speeding past, long headlight and taillight streaks, no people visible",
  "wide shot, slow shutter feel", None, None, None, "road_busy", [("motorbike_pass", "ބާރަށް", -16), ("car_pass", "ދުވެލީގައި", -16)], {}),
 ("Because of Hayaathu's careless move the sisters nearly had an accident. The alert driver of the oncoming car swerved and slammed the brakes so as not to hit them.",
  ["hayaathu", "dhooma"], "road", "blinding white headlights of a dark sedan stopped at an angle on the road, Hayaathu and Dhooma frozen in silhouette a safe distance in front of it, no contact",
  "low wide shot", None, "violence", "near-accident: no impact shown, only headlights and a stopped car at a safe distance", "road_busy",
  [("car_approach", "ކުރިމަތިން", -14), ("brake_screech", "ބުރެކި", -12)], {"hum": True}),
 ("In the glare of the headlights Dhooma screamed. The memory of the accident twelve years ago came rushing back.",
  ["dhooma"], "road", "Dhooma's face lit by harsh white headlight glare, eyes wide with terror, hands raised to shield her face, sitting in her wheelchair",
  "close-up", None, None, None, "road_busy", [("gasp", "ހަޅޭ", -18), ("heartbeat", "ހަނދާން", -16)], {"hum": True}),
 ("The pain became fresh. She relived the event that forced her to sit in a wheelchair for life.",
  [], "memory", "rain streaming down a car windscreen at night, blurred red and white lights beyond, hazy desaturated memory, no people",
  "close-up through glass", None, "violence", "memory of the fatal accident shown only as rain on a windscreen and blurred lights", "memory_rain",
  [("heartbeat", "ރިހުން", -16)], {"hum": True}),
 ("At Dhooma's scream Hayaathu screamed too. Having parked the car to one side, a handsome young man of about 25 stepped out.",
  ["young_driver"], "road", "the dark sedan parked at the roadside with headlights on, the young driver stepping out of the driver's door, frowning",
  "medium wide, low angle", None, None, None, "road_busy", [("car_door", "ޕާކުކުރުމަށްފަހު", -16)], {}),
 ("And came towards the two. 'What's your problem? Couldn't you find another car to die under?' the young man's harsh voice rang out.",
  ["young_driver"], "road", "the young driver striding towards the camera, angry frown, pointing, backlit by the car headlights",
  "medium shot, low angle", None, None, None, "road_busy", [("footsteps_pavement", "އައެވެ", -20)], {}),
 ("Frozen with fear, Hayaathu didn't seem to hear what the young man said. She quickly moved Dhooma's wheelchair aside and looked at her.",
  ["hayaathu", "dhooma"], "road", "Hayaathu crouching beside Dhooma's wheelchair at the roadside, looking anxiously into her sister's face, headlights blurred in the background",
  "medium shot", None, None, None, "road_busy", [("wheelchair_roll", "ވީލްޗެއާރ", -20)], {}),
 ("'Dhontha...' Hayaathu said anxiously. Dhooma, panicked and worried, gripped Hayaathu's hand tightly.",
  ["hayaathu", "dhooma"], "road", "close-up of two women's hands clasped tightly together on the armrest of a black wheelchair, teal and rose sleeves, trembling",
  "extreme close-up on hands", None, None, None, "road_busy", [], {}),
 ("In those few moments Dhooma was breathless with fear. The memory of twelve years ago still hasn't faded from her heart.",
  ["dhooma"], "road", "Dhooma breathing hard with her eyes shut tight, one hand pressed to her chest, streetlight on her face",
  "close-up", None, None, None, "road_busy", [("heartbeat", "ބިރުން", -16), ("breath_heavy", "ދާހިއްލާ", -22)], {"hum": True}),
 ("In that accident her mother and father left this world forever. And she was forced to rely on that chair for the rest of her life.",
  [], "memory", "a quiet Maldivian island cemetery at dusk, simple white coral-stone grave markers under palm trees, soft golden light, no people, no writing",
  "wide shot", None, "violence", "death shown as a peaceful cemetery at dusk", "night_exterior", [], {"hum": True}),
 ("'Sorry, sorry, sorry Dhontha... I don't know what's happening to me tonight, my mind just isn't working at all...'",
  ["hayaathu", "dhooma"], "road", "Hayaathu crying, holding her sister's hand in both of hers, Dhooma in the wheelchair looking at her, under a streetlight",
  "medium close-up", None, None, None, "street_night", [("sob_breath", "ސޮރީ", -24)], {}),
 ("Sobbing, she kissed Dhooma's hand. Dhooma, trying to calm her, began to speak with a stammer. 'Ha... Hayaathu...'",
  ["dhooma"], "road", "Dhooma, still shaken, trying to speak, lips parted, gentle loving eyes looking down at her sister",
  "close-up", None, "other", "kiss on the hand between sisters shown as the elder sister's tender reaction", "street_night", [], {}),
 ("'St... stop...' Dhooma managed with great difficulty. Whenever something frightening happens Dhooma can't speak properly.",
  ["dhooma"], "road", "(reuse) Dhooma breathless", "close-up", "shot_035", None, None, "street_night", [], {}),
 ("Fear stops her words. Hayaathu looked at Dhooma's face again and closed her tear-filled eyes. 'Let's go home Dhontha, you're very shaken.'",
  ["hayaathu"], "road", "Hayaathu closing her tear-filled eyes, head bowed, standing beside the wheelchair under a streetlight",
  "close-up", None, None, None, "street_night", [], {}),
 ("Hayaathu said, since Dhooma couldn't speak properly. Dhooma shook her head. 'H... h... home... if we go... Ma... Ma...'",
  ["dhooma"], "road", "(reuse) Dhooma trying to speak", "close-up", "shot_038", None, None, "street_night", [], {}),
 ("'Ma...' Dhooma struggled to say. 'Maaroof...' Hayaathu said softly. Dhooma nodded.",
  ["hayaathu", "dhooma"], "street", "the two sisters facing each other at the roadside under a warm streetlight, Dhooma nodding, Hayaathu looking down at her",
  "medium wide", None, None, None, "street_night", [], {}),
 ("'You mean if we go home I won't get to meet Maaroof?' Hayaathu asked bitterly.",
  ["hayaathu"], "street", "Hayaathu with a bitter, heartbroken expression, looking away, streetlight on her wet cheeks",
  "close-up", None, None, None, "street_night", [], {}),
 ("She was hurt that her beloved sister didn't know she had to sacrifice her love. And she smiled a bitter half-smile.",
  ["hayaathu"], "street", "(reuse) Hayaathu bitter", "close-up", "shot_043", None, None, "street_night", [], {"hum": True}),
 ("As if mocking her own helplessness. At Dhooma's words Hayaathu straightened up and pushed the chair on.",
  ["hayaathu", "dhooma"], "street", "Hayaathu pushing Dhooma's wheelchair away along the street, seen from behind, long shadows under streetlights",
  "wide shot from behind", None, None, None, "street_night", [("wheelchair_roll", "ދުއްވާލިއެވެ", -20)], {}),
 ("The young man, who stood listening, didn't know whether to step forward. When a message came to his phone he looked at it, turned and got into his car.",
  ["young_driver"], "road", "the young driver standing beside his dark sedan looking down at his phone, face lit by its glow, thoughtful",
  "medium shot", None, None, None, "road_busy", [("phone_buzz", "މެސެޖެއް", -18), ("car_door", "އެނބުރި", -16)], {}),
 ("Reaching a quiet part of the island they stopped to one side. From where Hayaathu stopped, the waves breaking in the distance looked beautiful.",
  ["hayaathu", "dhooma"], "beach", "Hayaathu and Dhooma small at the end of a paved path facing the moonlit sea, waves breaking white on the distant reef, seen from behind",
  "wide shot from behind", None, None, None, "beach_night", [("car_drive_off", "ރަށުގެ", -22)], {}),
 ("A quiet place away from the houses. Mostly lovers come to that spot.",
  [], "beach", "an empty wooden bench under leaning palm trees on a moonlit beach, calm lagoon, no people",
  "wide shot", None, "intimacy", "'lovers come here' shown as an empty bench, no couples", "beach_night", [], {}),
 ("Whenever Hayaathu wanted to meet Maaroof she came here. Since she couldn't go out alone, she always brought Dhooma.",
  ["hayaathu", "dhooma"], "beach", "Hayaathu sitting on the wooden bench beside Dhooma's wheelchair, both facing the moonlit sea, seen from behind",
  "medium wide from behind", None, None, None, "beach_night", [], {}),
 ("Because the doctor said Dhooma needs fresh natural air, her uncle has no objection.",
  ["dhooma"], "beach", "Dhooma with her eyes closed, face tilted up into the sea breeze, the edge of her hijab fluttering, peaceful",
  "close-up", None, None, None, "beach_night", [("wind_gust", "ތާޒާވައި", -20)], {}),
 ("Because looking after Dhooma is still their responsibility. But Waheed had decided that once Hayaathu married, that burden would fall on Hayaathu's head.",
  ["waheed"], "house_other", "Waheed sitting in an armchair in a dim room, arms crossed, cold stern frown, calculating",
  "medium shot, low angle", None, None, None, "living_night", [], {}),
 ("Waheed keeps the two only out of shame before the world, and for the property and money their father left for them.",
  ["waheed"], "house_other", "Waheed's heavy hand resting on a locked old metal cash box and a bundle of blank property papers tied with string on a wooden desk, lamp light",
  "close-up on desk", None, None, None, "living_night", [], {}),
 ("Neither Hayaathu nor Dhooma knows any of this. As far as they know, their father died in debt to the bank.",
  ["hayaathu", "dhooma"], "beach", "(reuse) sisters on the beach", "medium wide", "shot_049", None, None, "beach_night", [], {}),
 ("So they were told the bank had taken all the property. He had to pay for Hayaathu's education against his will, because of her grandfather.",
  ["hayaathu"], "bedroom", "Hayaathu studying at a small desk late at night with open textbooks and notebooks (blank pages), lamp light, focused",
  "medium shot", None, None, None, "room_night", [("page_turn", "ކިޔަވާދޭން", -22)], {}),
 ("Her grandfather's will said that if Hayaathu was not educated, he would not receive even an atom of his property.",
  [], "house_other", "an old folded parchment will with a red wax seal on a dark wooden table beside an old man's white skullcap and prayer beads, blank paper with no writing, warm lamp light",
  "close-up still life", None, None, None, "room_night", [], {}),
 ("Her grandfather too passed away within a year of her parents. There was no one left to wipe the tears of the two sisters.",
  [], "house_other", "an empty old wooden armchair by a window at dusk, a white skullcap resting on its seat, dust in a beam of fading light",
  "medium shot", None, "violence", "death shown as an empty chair with the grandfather's skullcap", "room_night", [], {"hum": True}),
 ("The two became each other's support. 'Dhontha, what do I do?' Hayaathu let out a deep sigh.",
  ["hayaathu", "dhooma"], "beach", "Hayaathu sitting on the bench holding Dhooma's hand, both silhouetted against the moonlit sea, Hayaathu's head bowed",
  "medium shot", None, None, None, "beach_night", [("sigh", "ނޭވާ", -18)], {}),
 ("'Should I surrender to uncle's wish?' Hayaathu asked, close to tears. 'Ha... Hayaathu, Dhon... Dhontha...'",
  ["hayaathu"], "beach", "Hayaathu's tearful face lit by moonlight, looking at her sister with pleading eyes, the sea behind her",
  "close-up", None, None, None, "beach_night", [], {"hum": True}),
 ("Dhooma tried to speak. 'What do I... Dhontha...' She knelt down beside Dhooma and began to talk.",
  ["hayaathu", "dhooma"], "beach", "Hayaathu kneeling on the path beside Dhooma's wheelchair, looking up at her sister and speaking earnestly, moonlit sea behind",
  "medium shot", None, None, None, "beach_night", [], {}),
 ("'The man Areesha was supposed to marry turned out to be very ugly — half his face was badly burned in an accident...'",
  ["areesha", "zoona"], "living", "flashback: Areesha and Zoona on the sofa looking at a smartphone together with disgusted expressions, the phone screen turned away from the viewer",
  "medium shot", None, "other", "the groom's burned face is never shown; only the women's reaction to a hidden phone screen", "living_night", [], {}),
 ("'I walked in while they were talking about it. I didn't even see the photo, but thinking of the accident I said it's not his fault that he's disfigured,'",
  ["hayaathu", "areesha", "zoona"], "living", "flashback: Hayaathu standing in a doorway speaking earnestly with an open hand, Areesha and Zoona on the sofa turning to look at her with surprise",
  "wide shot", None, None, None, "living_night", [], {}),
 ("'Look at the purity of the heart, not the face. Dhontha, did I say something wrong?' Hayaathu asked looking at Dhooma. Dhooma shook her head.",
  ["hayaathu", "dhooma"], "beach", "(reuse) Hayaathu kneeling by the wheelchair", "medium shot", "shot_059", None, None, "beach_night", [], {}),
 ("'Is it a crime that you sit in this chair, Dhontha?' Hayaathu said, crying harder. 'Because of what I said without thinking...'",
  ["hayaathu", "dhooma"], "beach", "Hayaathu kneeling and crying hard, one hand on the wheel of Dhooma's wheelchair, Dhooma's face crumpling with sorrow",
  "close-up", None, None, None, "beach_night", [("sob_breath", "ރޮވިފައި", -22)], {"hum": True}),
 ("Hayaathu began to sob. 'St... stop...' Dhooma said, stroking her cheek. Hayaathu laid her head in Dhooma's lap.",
  ["hayaathu", "dhooma"], "beach", "Hayaathu kneeling with her head resting on her sister's lap over the grey shawl, Dhooma's hand gently on her cheek, sisters comforting each other",
  "medium shot", None, None, None, "beach_night", [("sob_breath", "ގިސްލެވެން", -24)], {}),
 ("Dhooma kept stroking Hayaathu's head tenderly. 'My problem isn't his looks. It's his age...'",
  ["hayaathu", "dhooma"], "beach", "Dhooma stroking the head of Hayaathu who rests in her lap, Dhooma gazing out at the dark sea with sorrow",
  "medium close-up", None, None, None, "beach_night", [], {}),
 ("'And knowing I love Maaroof, why would uncle decide such a thing?' She started sobbing. 'What do I do, Dhontha...'",
  ["hayaathu", "dhooma"], "beach", "(reuse) head in lap", "medium shot", "shot_064", None, None, "beach_night", [("sob_breath", "ގިސްލެވެން", -24)], {}),
 ("'Uncle said that if I don't agree to marry that man, he'll stop your treatment, Dhontha...'",
  ["waheed"], "house_other", "flashback: Waheed standing in a dim hallway raising a finger in a cold warning, harsh overhead light, stern face",
  "medium shot, low angle", None, None, None, "living_night", [], {"hum": True}),
 ("Hayaathu kept sobbing with her head in Dhooma's lap. Dhooma gently stroked her head. Dhooma didn't know what more to say.",
  ["hayaathu", "dhooma"], "beach", "wide view from behind of the two sisters silhouetted against the moonlit sea, one kneeling with her head in the other's lap beside the wheelchair",
  "wide shot from behind", None, None, None, "beach_night", [], {}),
 ("Dhooma truly felt the wound in her little sister's heart. If it were in her power she would never let that marriage happen.",
  ["dhooma"], "beach", "Dhooma's face in moonlight, a tear in her eye, jaw set with quiet resolve",
  "close-up", None, None, None, "beach_night", [], {"hum": True}),
 ("She would not let her beloved sister's life be ruined. All of it was because of her. Her disability. 'Hayaathu...'",
  ["dhooma"], "beach", "close-up of the large wheel of the black wheelchair and Dhooma's still feet under the grey shawl, her hand gripping the wheel rim, moonlight",
  "close-up detail", None, None, None, "beach_night", [], {}),
 ("Dhooma wanted to say the words forming in her heart. But what her heart was saying gave her no strength to speak.",
  ["dhooma"], "beach", "(reuse) Dhooma resolute", "close-up", "shot_069", None, None, "beach_night", [], {}),
 ("Only her tears came to her aid. Faithfully, her tears spoke the feelings of her heart.",
  ["dhooma"], "beach", "a tear falling from Dhooma's cheek onto her hand resting on her sister's blush-pink headscarf, moonlit",
  "extreme close-up", None, None, None, "beach_night", [], {"hum": True}),
 ("Thinking of her disability, Dhooma felt even more heartbroken. Why were they sacrificing her little sister?",
  ["dhooma"], "beach", "(reuse) wheelchair wheel", "close-up detail", "shot_070", None, None, "beach_night", [], {}),
 ("Because the mother and father who loved them were gone. But she would not let it happen.",
  [], "beach", "the full moon slipping behind dark clouds over the sea, silver light on the waves",
  "wide shot", None, None, None, "beach_night", [], {}),
 ("She would not let her sister pay for her disability. She would not let her marry that man. Today she would make a decision.",
  ["dhooma"], "beach", "Dhooma in profile looking out at the dark sea with determined eyes, wind moving her hijab, moonlight rim light",
  "close-up profile", None, None, None, "beach_night", [("wind_gust", "ނިންމުމެއް", -20)], {"hum": True}),
 ("Otherwise her sister would have to bear heartbreak and grief every day of her life. She would not allow it.",
  ["dhooma"], "beach", "(reuse) Dhooma determined", "close-up profile", "shot_075", None, None, "beach_night", [], {"hum": True}),
 ("She gently stroked the head of Hayaathu, who lay crying in her lap. For Hayaathu, her sister's lap is a shelter.",
  ["hayaathu", "dhooma"], "beach", "(reuse) Dhooma stroking her head", "medium close-up", "shot_065", None, None, "beach_night", [], {}),
 ("Whenever Hayaathu is hurt by uncle's temper, Dhooma's lap becomes her shelter. Because of grandfather's will, uncle doesn't dare touch Dhooma.",
  [], "house_other", "a large looming shadow of a man on a hallway wall, a teacup knocked over on the tiled floor, spilled tea, tense harsh light, no person visible",
  "medium shot", None, "violence", "the uncle's abuse shown only as his shadow and a spilled cup", "living_night", [("cup_clatter", "ރުޅިގަދަ", -16)], {"hum": True}),
 ("Everything falls on the helpless Hayaathu. The darkness of the night, the silence of the place, the waves on the shore and the blowing wind shared the two sisters' sorrow.",
  ["hayaathu", "dhooma"], "beach", "very wide shot of the dark beach at night, waves rolling onto the sand, palms bending in the wind, two tiny silhouettes, one in a wheelchair, at the end of the path",
  "very wide shot", None, None, None, "beach_night", [("wind_gust", "ވަޔަކީ", -18), ("wave_crash", "ރާލުގެ", -18)], {}),
 ("The two poured out to each other, through tears, the feelings and heartache in their hearts. 'Hayaathu...'",
  ["hayaathu", "dhooma"], "beach", "(reuse) sisters silhouetted", "wide shot from behind", "shot_068", None, None, "beach_night", [], {}),
 ("Maaroof's voice came from very close. Hayaathu quickly lifted her head and wiped her tears. Dhooma too hurried to wipe hers. 'Why are you crying?'",
  ["maaroof", "hayaathu", "dhooma"], "beach", "Maaroof standing a few steps away on the path in the moonlight looking concerned; in the foreground Hayaathu lifting her head and wiping her tears beside Dhooma's wheelchair",
  "medium wide", None, None, None, "beach_night", [("footsteps_sand", "ގާތުން", -20)], {}),
 ("Maaroof asked. 'Nothing...' Hayaathu said, getting up. 'How are you, Dhooma?' Maaroof asked her. Dhooma smiled.",
  ["maaroof", "dhooma"], "beach", "Maaroof standing at a respectful distance with his hands at his sides, greeting Dhooma with a polite nod, Dhooma in her wheelchair giving him a small brave smile, no touching, no handshake, moonlit sea behind",
  "medium shot", None, None, None, "beach_night", [], {}),
 ("Seeing Hayaathu's and Dhooma's eyes red from crying, Maaroof knew something serious had happened. Maaroof took Hayaathu's hand.",
  ["maaroof"], "beach", "Maaroof's face full of concern, brows drawn together, looking at Hayaathu off-screen, moonlight",
  "close-up", None, "intimacy", "hand-holding not shown; his concerned face instead", "beach_night", [], {}),
 ("Giving the two some space, Dhooma turned her chair and rolled slowly ahead. 'What happened, why are you two crying?'",
  ["dhooma"], "beach", "Dhooma rolling her wheelchair slowly away along the moonlit path towards the sea, seen from behind, alone",
  "wide shot from behind", None, None, None, "beach_night", [("wheelchair_roll", "އަނބުރާލިއެވެ", -20)], {}),
 ("Maaroof asked lovingly, drawing her close. 'Maaroof, let's get married,' Hayaathu said softly, resting her head on his chest.",
  ["hayaathu", "maaroof"], "beach", "Hayaathu and Maaroof standing a respectful arm's length apart facing each other on the moonlit beach, silhouetted, no touching",
  "wide silhouette shot", None, "intimacy", "embrace and head on chest replaced by two silhouettes at a respectful distance", "beach_night", [], {}),
 ("'Let's — but will your uncle let us marry? I'm still struggling to meet his condition.'",
  ["maaroof"], "beach", "Maaroof looking down with a troubled frown, the moonlit sea behind him",
  "medium close-up", None, None, None, "beach_night", [], {}),
 ("Maaroof said, holding her tight. 'Fine, then let's run away and take Dhontha,' Hayaathu said, almost in tears. Maaroof eased her away from him.",
  ["hayaathu"], "beach", "Hayaathu's desperate tearful face, pleading, wind moving her blush-pink hijab, moonlight",
  "close-up", None, "intimacy", "the hug is not shown; her pleading face instead", "beach_night", [], {"hum": True}),
 ("And looked straight into her red, tearful eyes. 'Dhoonya, this is the Maldives — where could we possibly run to?'",
  ["maaroof", "hayaathu"], "beach", "over-the-shoulder shot from behind Hayaathu: Maaroof an arm's length away looking earnestly into her eyes, no touching",
  "over-the-shoulder", None, None, None, "beach_night", [], {}),
 ("'Besides, I don't want to win my love that way. Insha Allah I will find the three million rufiyaa; that's not too much to win my love.'",
  ["maaroof"], "beach", "Maaroof with a determined sincere expression, hand on his own chest, moonlit sea and palms behind him",
  "medium close-up", None, None, None, "beach_night", [], {}),
 ("Maaroof said, stroking her cheek. 'I'll take you both out of that house with dignity. Trust me...'",
  ["hayaathu"], "beach", "Hayaathu's face softening with a faint fragile hope, tears glistening, moonlight",
  "close-up", None, "intimacy", "touching her cheek not shown; her hopeful face instead", "beach_night", [], {}),
 ("Before Maaroof could finish, they heard the sound of something falling into the sea. Startled, both turned towards the sound.",
  [], "beach", "a sudden splash and spreading ripples on the dark moonlit sea near the shore, spray in the air, ominous, no person visible",
  "wide shot", None, "other", "cliffhanger: only a splash on the water, nothing falling shown", "beach_night", [("splash", "މޫދަށް", -10), ("heartbeat", "ސިހިފައި", -16)], {"hum": True}),
]

MOTIONS = ["slow push-in", "pan left", "slow pull-out", "pan right", "slow push-in", "pan up", "slow pull-out", "pan down", "static drift"]

if __name__ == "__main__":
    ep_dir = sys.argv[1]
    segs = json.load(open(f"{ep_dir}/work/segments.json", encoding="utf-8"))
    words = json.load(open(f"{ep_dir}/work/episode-272-captions.json", encoding="utf-8"))[0]["words"]
    assert len(segs) == len(S), (len(segs), len(S))
    scenes = []
    for i, (seg, s) in enumerate(zip(segs, S)):
        en, chars, loc, visual, camera, img, sens, safe, amb, sfx, extra = s
        sfx_out = []
        for name, key, g in sfx:
            hit = next((w for w in words[seg["w0"]:seg["w1"] + 1] if key in w["word"]), None)
            assert hit, (seg["id"], key)
            sfx_out.append({"name": name, "atMs": hit["startMs"], "gainDb": g, "word": hit["word"]})
        scenes.append({
            "id": seg["id"], "startMs": seg["startMs"], "endMs": seg["endMs"],
            "narration_dhivehi": seg["narration_dhivehi"], "narration_english": en,
            "characters": chars, "location": LOC[loc], "location_key": loc,
            "visual": visual, "camera": camera, "motion": MOTIONS[i % len(MOTIONS)],
            "image": f"images/{img}.png" if img else f"images/{seg['id']}.png",
            "reuse_of": img, "sensitive": sens, "safe_substitution": safe,
            "ambience": amb, "sfx": sfx_out, "hum": bool(extra.get("hum")),
            "prompt_attempts": [],
        })
    json.dump(scenes, open(f"{ep_dir}/scenes.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    new = sum(1 for s in scenes if not s["reuse_of"])
    print(len(scenes), "shots,", new, "new images,", len(scenes) - new, "reused")
